### ISSUE TITLE
Unable to start ui

### ISSUE THREAD

**Issue by arun2dot0** [otrebski/reactive-missile-defend#6]
Followed instructions and running Cassandra on Docker . When I start up the ui "sbt ui" . I keep getting this issue
background log: info: Creating status keeper
background log: info: Creating status keeper proxy
background log: info: Starting
background log: error: Exception in thread "main" java.lang.ExceptionInInitializerError
background log: error:  at defend.ui.UiApp.main(UiApp.scala)
background log: error: Caused by: java.lang.IllegalArgumentException: input == null!
background log: error:  at javax.imageio.ImageIO.read(ImageIO.java:1348)
background log: error:  at defend.ui.JWarTheater.<init>(JWarTheater.scala:75)
background log: error:  at defend.ui.UiApp$.<init>(UiApp.scala:79)
background log: error:  at defend.ui.UiApp$.<clinit>(UiApp.scala)
background log: error:  ... 1 more
background log: error: Uncaught error from thread [defend-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[defend]
background log: error: java.lang.NoClassDefFoundError: Could not initialize class defend.ui.UiApp$
background log: error:  at defend.ui.UiApp$$anonfun$4.apply(UiApp.scala:32)
background log: error:  at defend.ui.UiApp$$anonfun$4.apply(UiApp.scala:32)
background log: error:  at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
background log: error:  at akka.actor.Props.newActor(Props.scala:213)
background log: error:  at akka.actor.ActorCell.newActor(ActorCell.scala:562)
background log: error:  at akka.actor.ActorCell.create(ActorCell.scala:588)
background log: error:  at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
background log: error:  at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
background log: error:  at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
background log: error:  at akka.dispatch.Mailbox.run(Mailbox.scala:223)
background log: error:  at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
background log: error:  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
background log: error:  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
background log: error:  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
background log: error:  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by otrebski** [comment]
Looks like I did not committed icon. It is fixed, please retry.
